/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.munger.passwordkeeper.view;

import com.munger.passwordkeeper.Main;
import com.munger.passwordkeeper.struct.documents.PasswordDocument;
import java.awt.event.ActionEvent;

/**
 *
 * @author hallmarklabs
 */
public class NewFile extends javax.swing.JPanel {

    /**
     * Creates new form NewFile
     */
    public NewFile() 
    {
        initComponents();
        submitBtn.addActionListener((ActionEvent e) -> 
        {
            doSubmit();
        });
    }
    
    private void doSubmit()
    {
        char[] ps1 = password1ipt.getPassword();
        char[] ps2 = password2ipt.getPassword();
        
        boolean valid = validate(ps1, ps2);
        
        if (!valid)
            return;
        
        try
        {
            PasswordDocument doc = Main.instance.mainState.document;
            doc.setPassword(new String(ps1));
            doc.load(true);
        }
        catch(Exception e){
            return;
        }
        
        Main.instance.loadDocumentView();
    }
    
    private boolean validate(char[] ps1, char[] ps2)
    {
        int sz = ps1.length;
        int sz2 = ps2.length;
        
        if (sz != sz2)
            return false;
        
        for (int i = 0; i < sz; i++)
        {
            if (ps1[i] != ps2[i])
                return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        password1ipt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        password2ipt = new javax.swing.JPasswordField();
        submitBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);

        password1ipt.setMinimumSize(new java.awt.Dimension(100, 26));
        password1ipt.setPreferredSize(new java.awt.Dimension(120, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(password1ipt, gridBagConstraints);

        jLabel2.setText("Verify Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jLabel2, gridBagConstraints);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        password2ipt.setPreferredSize(new java.awt.Dimension(120, 26));
        password2ipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2iptActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(password2ipt, gridBagConstraints);

        submitBtn.setText("Create Password Repo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        add(submitBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void password2iptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2iptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2iptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField password1ipt;
    private javax.swing.JPasswordField password2ipt;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
