/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_munger_passwordkeeper_struct_AES256 */

#ifndef _Included_com_munger_passwordkeeper_struct_AES256
#define _Included_com_munger_passwordkeeper_struct_AES256
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jbyteArray JNICALL Java_com_munger_passwordkeeper_struct_AES256_init
  (JNIEnv *, jobject, jstring, jint);

JNIEXPORT void JNICALL Java_com_munger_passwordkeeper_struct_AES256_destroy
        (JNIEnv*, jobject, jbyteArray);

JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_encode
  (JNIEnv *, jobject, jbyteArray, jstring);


JNIEXPORT jbyteArray JNICALL Java_com_munger_passwordkeeper_struct_AES256_encodeToBytes
        (JNIEnv *, jobject, jbyteArray, jstring);

JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_decode
  (JNIEnv *, jobject, jbyteArray, jstring);

JNIEXPORT jfloat JNICALL Java_com_munger_passwordkeeper_struct_AES256_getDecodeProgress
        (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_munger_passwordkeeper_struct_AES256_getDecodeIsDone
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_decodeFromBytes
        (JNIEnv *, jobject, jbyteArray, jbyteArray);

JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_md5Hash
        (JNIEnv*, jobject, jstring);


JNIEXPORT jfloat JNICALL Java_com_munger_passwordkeeper_struct_AES256_getDecodeProgress
        (JNIEnv * env, jobject jthis);

#ifdef __cplusplus
}
#endif
#endif
