/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.munger.passwordkeeper.view.widget;

/**
 *
 * @author hallmarklabs
 */
public class LabelAndTextEdit extends javax.swing.JPanel {

    /**
     * Creates new form LabelAndTextEdit
     */
    public LabelAndTextEdit() {
        initComponents();
        
        input.setVisible(false);
    }
    
    private boolean editable = false;
    
    public boolean getEditable()
    {
        return editable;
    }
    
    public void setEditable(boolean value)
    {
        editable = value;
        
        input.setVisible(editable);
        label.setVisible(!editable);
        
        label.setText(input.getText());
    }
    
    public String getText()
    {
        if (editable)
            return input.getText();
        else
            return label.getText();
    }
    
    public void setText(String value)
    {
        input.setText(value);
        label.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        input = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        label.setText("jLabel1");
        label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(label, java.awt.BorderLayout.CENTER);

        input.setText("jTextField1");
        add(input, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
