/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_munger_passwordkeeper_struct_AES256 */

#ifndef _Included_com_munger_passwordkeeper_struct_AES256
#define _Included_com_munger_passwordkeeper_struct_AES256
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_munger_passwordkeeper_struct_AES256_init
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_munger_passwordkeeper_struct_AES256_destroy
  (JNIEnv *, jobject, jint);

JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_encode
  (JNIEnv *, jobject, jint, jstring);


JNIEXPORT jbyteArray JNICALL Java_com_munger_passwordkeeper_struct_AES256_encodeToBytes
        (JNIEnv *, jobject, jint, jstring);

JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_decode
  (JNIEnv *, jobject, jint, jstring);


JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_decodeFromBytes
        (JNIEnv *, jobject, jint, jbyteArray);


JNIEXPORT jstring JNICALL Java_com_munger_passwordkeeper_struct_AES256_md5Hash
        (JNIEnv*, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
